package app.cash.tanvir.info.util.report

import android.content.Context
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import app.cash.tanvir.info.domain.model.Sheet
import app.cash.tanvir.info.util.CurrencyFormatter
import app.cash.tanvir.info.util.NumberToWordsConverter
import java.io.ByteArrayOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Generates PDF reports using Android's native [PdfDocument] framework.
 */
object PdfReportGenerator {

    fun generatePdf(context: Context? = null, sheet: Sheet, isBangla: Boolean = false): ByteArray {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 page dimensions in points
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas

        val paint = Paint().apply {
            isAntiAlias = true
            color = Color.BLACK
        }

        context?.let { ctx ->
            try {
                val banglaTypeface = Typeface.createFromAsset(ctx.assets, "fonts/tiro_bangla.ttf")
                paint.typeface = banglaTypeface
            } catch (_: Exception) {}
        }

        var y = 50f

        // Title Header
        paint.textSize = 24f
        paint.isFakeBoldText = true
        paint.color = Color.parseColor("#00695C") // Deep Teal
        canvas.drawText("Cash Report", 40f, y, paint)

        y += 25f
        paint.textSize = 12f
        paint.isFakeBoldText = false
        paint.color = Color.DKGRAY
        val dateFormat = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
        canvas.drawText("Date: ${dateFormat.format(Date(sheet.updatedAt))}", 40f, y, paint)

        y += 20f
        canvas.drawLine(40f, y, 555f, y, paint)
        y += 30f

        // Summary Card
        paint.textSize = 18f
        paint.isFakeBoldText = true
        paint.color = Color.BLACK
        val totalFormatted = CurrencyFormatter.format(sheet.grandTotal, useBengaliDigits = isBangla)
        canvas.drawText("Grand Total: $totalFormatted", 40f, y, paint)

        y += 20f
        paint.textSize = 11f
        paint.isFakeBoldText = false
        val words = if (isBangla) NumberToWordsConverter.toBangla(sheet.grandTotal) else NumberToWordsConverter.toEnglish(sheet.grandTotal)
        canvas.drawText("In Words: $words", 40f, y, paint)

        y += 20f
        canvas.drawText("Total Pieces: ${sheet.totalPieces}  |  Active Denominations: ${sheet.activeDenominations}", 40f, y, paint)

        y += 30f
        canvas.drawLine(40f, y, 555f, y, paint)
        y += 25f

        // Breakdown Table Header
        paint.textSize = 14f
        paint.isFakeBoldText = true
        canvas.drawText("Denomination", 40f, y, paint)
        canvas.drawText("Quantity", 250f, y, paint)
        canvas.drawText("Subtotal", 440f, y, paint)

        y += 10f
        canvas.drawLine(40f, y, 555f, y, paint)
        y += 20f

        // Breakdown Items (exclude 0 quantity)
        paint.textSize = 12f
        paint.isFakeBoldText = false

        val activeRows = sheet.rows.filter { it.quantity > 0 }
        if (activeRows.isEmpty()) {
            canvas.drawText("No cash counted.", 40f, y, paint)
        } else {
            activeRows.forEach { row ->
                val denomLabel = if (isBangla) row.denomination.labelBn else row.denomination.label
                val subtotalFormatted = CurrencyFormatter.format(row.total, useBengaliDigits = isBangla)

                canvas.drawText(denomLabel, 40f, y, paint)
                canvas.drawText(row.quantity.toString(), 250f, y, paint)
                canvas.drawText(subtotalFormatted, 440f, y, paint)
                y += 22f
            }
        }

        y += 15f
        canvas.drawLine(40f, y, 555f, y, paint)
        y += 30f

        // Footer
        paint.textSize = 10f
        paint.color = Color.GRAY
        canvas.drawText("Generated by Cash Figure App", 40f, y, paint)

        pdfDocument.finishPage(page)

        val stream = ByteArrayOutputStream()
        pdfDocument.writeTo(stream)
        pdfDocument.close()
        return stream.toByteArray()
    }
}
