package app.cash.tanvir.info.util.report

import app.cash.tanvir.info.domain.model.Sheet
import app.cash.tanvir.info.util.CurrencyFormatter
import app.cash.tanvir.info.util.NumberToWordsConverter

object TxtReportGenerator {

    fun generateTxt(sheet: Sheet, isBangla: Boolean = false): ByteArray {
        val dateStr = formatTxtDate(sheet.updatedAt, isBangla)
        val words = if (isBangla) NumberToWordsConverter.toBangla(sheet.grandTotal) else NumberToWordsConverter.toEnglish(sheet.grandTotal)
        val totalPiecesStr = if (isBangla) app.cash.tanvir.info.util.BanglaDigitConverter.toBangla(sheet.totalPieces) else sheet.totalPieces.toString()
        val activeDenomStr = if (isBangla) app.cash.tanvir.info.util.BanglaDigitConverter.toBangla(sheet.activeDenominations) else sheet.activeDenominations.toString()

        val sb = StringBuilder()
        sb.append("=========================================\n")
        sb.append(if (isBangla) "              ক্যাশ রিপোর্ট               \n" else "               CASH REPORT               \n")
        sb.append("=========================================\n")
        sb.append(if (isBangla) "তারিখ: $dateStr\n" else "Date: $dateStr\n")
        sb.append(if (isBangla) "সর্বমোট: ${CurrencyFormatter.format(sheet.grandTotal, useBengaliDigits = true)}\n" else "Grand Total: ${CurrencyFormatter.format(sheet.grandTotal, useBengaliDigits = false)}\n")
        sb.append(if (isBangla) "কথায়: $words\n" else "In Words: $words\n")
        sb.append(if (isBangla) "মোট নোট: $totalPiecesStr\n" else "Total Pieces: $totalPiecesStr\n")
        sb.append(if (isBangla) "নোটের ধরণ: $activeDenomStr\n" else "Active Denominations: $activeDenomStr\n")
        val notesText = if (sheet.remark.isNotBlank()) sheet.remark else "N/A"
        sb.append(if (isBangla) "নোট: $notesText\n" else "Notes: $notesText\n")
        sb.append("-----------------------------------------\n")
        sb.append(if (isBangla) "নোটের বিস্তারিত হিসাব:\n" else "CASH BREAKDOWN:\n")

        val activeRows = sheet.rows.filter { it.quantity > 0 }
        if (activeRows.isEmpty()) {
            sb.append(if (isBangla) "কোনো হিসাব নেই।\n" else "No cash counted.\n")
        } else {
            activeRows.forEach { row ->
                val denomLabel = if (isBangla) row.denomination.labelBn else row.denomination.label
                val subtotal = CurrencyFormatter.format(row.total, useBengaliDigits = isBangla)
                if (isBangla) {
                    val qtyStr = app.cash.tanvir.info.util.BanglaDigitConverter.toBangla(row.quantity)
                    sb.append("$denomLabel × $qtyStr = $subtotal\n")
                } else {
                    sb.append(String.format("%-10s x %-8d = %s\n", denomLabel, row.quantity, subtotal))
                }
            }
        }

        sb.append("=========================================\n")
        sb.append(if (isBangla) "ক্যাশ ফিগার অ্যাপ দ্বারা প্রস্তুতকৃত\n" else "Generated by Cash Figure App\n")

        val content = sb.toString().toByteArray(Charsets.UTF_8)
        // Prepend UTF-8 BOM so text editors correctly interpret Bangla text
        return if (isBangla) {
            val bom = byteArrayOf(0xEF.toByte(), 0xBB.toByte(), 0xBF.toByte())
            bom + content
        } else {
            content
        }
    }

    private fun formatTxtDate(timestamp: Long, isBangla: Boolean): String {
        return app.cash.tanvir.info.util.DateTimeFormatter.format(timestamp, isBangla)
    }
}
