package app.cash.tanvir.info.util.report

import app.cash.tanvir.info.domain.model.Sheet
import app.cash.tanvir.info.util.CurrencyFormatter
import app.cash.tanvir.info.util.NumberToWordsConverter
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object TxtReportGenerator {

    fun generateTxt(sheet: Sheet, isBangla: Boolean = false): ByteArray {
        val dateFormat = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
        val dateStr = dateFormat.format(Date(sheet.updatedAt))
        val words = if (isBangla) NumberToWordsConverter.toBangla(sheet.grandTotal) else NumberToWordsConverter.toEnglish(sheet.grandTotal)

        val sb = StringBuilder()
        sb.append("=========================================\n")
        sb.append("         CASH FIGURE CASH REPORT         \n")
        sb.append("=========================================\n")
        sb.append("Date: $dateStr\n")
        sb.append("Grand Total: ${CurrencyFormatter.format(sheet.grandTotal, useBengaliDigits = isBangla)}\n")
        sb.append("In Words: $words\n")
        sb.append("Total Pieces: ${sheet.totalPieces}\n")
        sb.append("Active Denominations: ${sheet.activeDenominations}\n")
        sb.append("-----------------------------------------\n")
        sb.append("CASH BREAKDOWN:\n")

        val activeRows = sheet.rows.filter { it.quantity > 0 }
        if (activeRows.isEmpty()) {
            sb.append("No cash counted.\n")
        } else {
            activeRows.forEach { row ->
                val denomLabel = if (isBangla) row.denomination.labelBn else row.denomination.label
                val subtotal = CurrencyFormatter.format(row.total, useBengaliDigits = isBangla)
                sb.append(String.format("%-10s x %-8d = %s\n", denomLabel, row.quantity, subtotal))
            }
        }

        sb.append("=========================================\n")
        sb.append("Generated by Cash Figure App\n")

        return sb.toString().toByteArray(Charsets.UTF_8)
    }
}
